# Generated by Django 4.2 on 2025-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
