# Generated by Django 4.2 on 2025-09-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('client_type', models.CharField(max_length=100)),
            ],
        ),
    ]
